name: Create Release Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 0.1.12)'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Use PAT instead of GITHUB_TOKEN to ensure the tag push triggers the release workflow
          token: ${{ secrets.RELEASE_PAT }}
      
      - name: Update version in __init__.py
        run: |
          sed -i "s/__version__ = \".*\"/__version__ = \"${{ github.event.inputs.version }}\"/" src/cylestio_local_server/__init__.py
      
      - name: Update version in pyproject.toml
        run: |
          sed -i "s/version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml
      
      - name: Commit version changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/cylestio_local_server/__init__.py pyproject.toml
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
      
      - name: Create and push tag
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Release version ${{ github.event.inputs.version }}"
          git push origin main
          git push origin v${{ github.event.inputs.version }} 