name: Manual Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.12)'
        required: true
      test_pypi:
        description: 'Publish to Test PyPI first'
        type: boolean
        default: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel twine pytest pytest-cov httpx requests psutil
        pip install -e .[dev]
    
    - name: Update version in __init__.py
      run: |
        sed -i "s/__version__ = \".*\"/__version__ = \"${{ github.event.inputs.version }}\"/" src/cylestio_local_server/__init__.py
    
    - name: Update version in pyproject.toml
      run: |
        sed -i "s/version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml
    
    - name: Run basic tests
      run: |
        pytest -xvs tests/test_api_minimal.py || echo "Some tests failed but continuing"
    
    - name: Build package
      run: |
        python -m build
        
    - name: Check distribution
      run: |
        python -m twine check dist/*
        
    - name: Publish to Test PyPI
      if: ${{ github.event.inputs.test_pypi == 'true' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }} 